import http from 'node:http';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { randomUUID, createHash } from 'node:crypto';
import path from 'node:path';
const root=path.resolve(new URL('..',import.meta.url).pathname); const dataDir=path.join(root,'data'); const db=path.join(dataDir,'crm.json');
const statuses=['Request','Analyse','Clarify','Approve','Assign','Develop','Review','QA','UAT','Deploy','Verify','Resolve','Close','On Hold','Blocked','Rejected','Cancelled','Reopened'];
const transitions={Request:['Analyse','Cancelled','On Hold','Blocked'],Analyse:['Clarify','Approve','Rejected','On Hold','Blocked'],Clarify:['Approve','Analyse','On Hold'],Approve:['Assign','Rejected','On Hold'],Assign:['Develop','On Hold'],Develop:['Review','On Hold','Blocked'],Review:['QA','Develop','Rejected'],QA:['UAT','Develop','Blocked'],UAT:['Deploy','Develop','Rejected'],Deploy:['Verify','Blocked'],Verify:['Resolve','Reopened','Blocked'],Resolve:['Close','Reopened'],Close:['Reopened'], 'On Hold':['Reopened','Cancelled'],Blocked:['Reopened','Cancelled'],Rejected:['Reopened'],Cancelled:['Reopened'],Reopened:['Analyse']};
const seed={users:[{id:'u-admin',username:'admin',name:'Admin User',password:hash('Admin123!'),role:'Admin',projectIds:[]}],projects:[],tickets:[],tasks:[],comments:[],notifications:[],audit:[],attachments:[]};
function hash(v){return createHash('sha256').update(v).digest('hex')}; async function load(){if(!existsSync(db)){await mkdir(dataDir,{recursive:true}); await writeFile(db,JSON.stringify(seed,null,2))} return JSON.parse(await readFile(db,'utf8'))}; async function save(x){await writeFile(db,JSON.stringify(x,null,2))};
function json(res,status,body){res.writeHead(status,{'content-type':'application/json','access-control-allow-origin':'*'});res.end(JSON.stringify(body))}; function body(req){return new Promise((ok,no)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){no(e)}})})};
async function handler(req,res){if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,PATCH,DELETE,OPTIONS','access-control-allow-headers':'content-type'});return res.end()}; const u=new URL(req.url,'http://localhost'); const parts=u.pathname.split('/').filter(Boolean); const d=await load();
if(parts[0]==='api'){try{if(req.method==='POST'&&parts[1]==='login'){const b=await body(req), user=d.users.find(x=>x.username===b.username&&x.password===hash(b.password)); return user?json(res,200,{user:{...user,password:undefined},token:user.id}):json(res,401,{error:'Invalid username or password'})}
if(req.method==='GET'&&parts[1]==='meta')return json(res,200,{statuses,transitions,sla:{Critical:['1 hour','4 hours'],High:['4 hours','1 business day'],Medium:['1 business day','3 business days'],Low:['2 business days','5 business days']},slaNote:'Pending management confirmation'});
const collection=parts[1]; const map={projects:'projects',tickets:'tickets',tasks:'tasks',comments:'comments',notifications:'notifications',audit:'audit',attachments:'attachments'}; if(map[collection]){const key=map[collection]; if(req.method==='GET')return json(res,200,d[key]); if(req.method==='POST'){const b=await body(req); const item={id:randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),...b}; if(key==='tickets'){item.status=item.status||'Request';item.priority=item.priority||'Medium';item.history=[{status:item.status,at:item.createdAt,by:'u-admin'}]} d[key].push(item); if(key==='tickets')d.audit.push({id:randomUUID(),entity:'ticket',entityId:item.id,action:'created',at:item.createdAt,by:'u-admin'}); await save(d); return json(res,201,item)} if(parts[2]&&['PATCH','DELETE'].includes(req.method)){const i=d[key].findIndex(x=>x.id===parts[2]);if(i<0)return json(res,404,{error:'Not found'});if(req.method==='DELETE'){d[key].splice(i,1);await save(d);return json(res,204,{})}const b=await body(req), old=d[key][i]; if(key==='tickets'&&b.status&&b.status!==old.status&&!((transitions[old.status]||[]).includes(b.status)))return json(res,422,{error:`Invalid transition ${old.status} → ${b.status}`,allowed:transitions[old.status]||[]}); d[key][i]={...old,...b,updatedAt:new Date().toISOString()}; if(key==='tickets'&&b.status!==old.status)d[key][i].history=[...(old.history||[]),{status:b.status,at:new Date().toISOString(),by:'u-admin'}];d.audit.push({id:randomUUID(),entity:key.slice(0,-1),entityId:old.id,action:'updated',changes:b,at:new Date().toISOString(),by:'u-admin'});await save(d);return json(res,200,d[key][i])}}
if(req.method==='GET'&&parts[1]==='dashboard')return json(res,200,{projects:d.projects.length,tickets:d.tickets.length,open:d.tickets.filter(x=>!['Close','Cancelled','Rejected'].includes(x.status)).length,byStatus:Object.fromEntries(statuses.map(s=>[s,d.tickets.filter(x=>x.status===s).length]))}); return json(res,404,{error:'Route not found'})}catch(e){return json(res,400,{error:e.message})}}
if(req.method==='GET'){let file=parts.length?path.join(root,'public',...parts):path.join(root,'public','index.html');if(!existsSync(file))file=path.join(root,'public','index.html');res.writeHead(200,{'content-type':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html'});return res.end(await readFile(file))}json(res,404,{error:'Not found'})}
await load(); http.createServer((q,s)=>handler(q,s)).listen(process.env.PORT||3000,()=>console.log(`CRM running on http://localhost:${process.env.PORT||3000}`));
