import { DatabaseSync } from 'node:sqlite';
import { randomUUID } from 'node:crypto';
import path from 'node:path';
const file = process.env.CRM_DATA_FILE || path.resolve('data/crm.sqlite');
const db = new DatabaseSync(file);
const now = new Date().toISOString();
const admin = db.prepare("SELECT id FROM users WHERE username='admin'").get();
const projectId = 'p-demo';
db.prepare('INSERT OR REPLACE INTO projects VALUES (?,?,?,?,?,?)').run(projectId,'Internal CRM MVP','Demo delivery workspace',admin.id,'Active',now);
const project = {id:projectId,name:'Internal CRM MVP',description:'Demo delivery workspace',ownerId:admin.id,status:'Active'};
db.prepare('INSERT OR REPLACE INTO resources VALUES (?,?,?,?,?,?)').run('projects',projectId,JSON.stringify(project),projectId,now,now);
db.prepare('INSERT OR IGNORE INTO memberships VALUES (?,?,?)').run(admin.id,projectId,'Admin');
const ticket = {id:'t-demo',key:'CRM-00001',title:'Create intake workflow',description:'Configure request intake and lifecycle tracking.',projectId,priority:'High',status:'Develop',assigneeId:admin.id,history:[{status:'Request',at:now,actorId:admin.id},{status:'Analyse',at:now,actorId:admin.id},{status:'Develop',at:now,actorId:admin.id}]};
db.prepare('INSERT OR REPLACE INTO resources VALUES (?,?,?,?,?,?)').run('tickets',ticket.id,JSON.stringify(ticket),projectId,now,now);
db.prepare('INSERT OR REPLACE INTO counters VALUES (?,?)').run('ticket',1);
const task = {id:randomUUID(),title:'Define acceptance criteria',ticketId:ticket.id,projectId,status:'In Progress'};
db.prepare('INSERT OR REPLACE INTO resources VALUES (?,?,?,?,?,?)').run('tasks',task.id,JSON.stringify(task),projectId,now,now);
console.log('Seeded SQLite CRM data.');
